# Form implementation generated from reading ui file 'MainMenu.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.MenuLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.MenuLabel.setGeometry(QtCore.QRect(10, 10, 561, 141))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.MenuLabel.setFont(font)
        self.MenuLabel.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.MenuLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.MenuLabel.setObjectName("MenuLabel")
        self.VoteScreenButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.VoteScreenButton.setGeometry(QtCore.QRect(190, 140, 211, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.VoteScreenButton.setFont(font)
        self.VoteScreenButton.setObjectName("VoteScreenButton")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(190, 300, 211, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 450, 211, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        MainMenu.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainMenu)
        self.statusbar.setObjectName("statusbar")
        MainMenu.setStatusBar(self.statusbar)

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "MainWindow"))
        self.MenuLabel.setText(_translate("MainMenu", "MENU"))
        self.VoteScreenButton.setText(_translate("MainMenu", "Vote"))
        self.pushButton.setText(_translate("MainMenu", "Candidates"))
        self.pushButton_2.setText(_translate("MainMenu", "Results"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainMenu = QtWidgets.QMainWindow()
    ui = Ui_MainMenu()
    ui.setupUi(MainMenu)
    MainMenu.show()
    sys.exit(app.exec())
