# Form implementation generated from reading ui file 'NigilScreen.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NigilScreen(object):
    def setupUi(self, NigilScreen):
        NigilScreen.setObjectName("NigilScreen")
        NigilScreen.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(16)
        NigilScreen.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=NigilScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.nigil_profile_image = QtWidgets.QLabel(parent=self.centralwidget)
        self.nigil_profile_image.setGeometry(QtCore.QRect(100, 10, 221, 321))
        self.nigil_profile_image.setStyleSheet("image: url(:/newPrefix/nigil_johnson.jpg);")
        self.nigil_profile_image.setText("")
        self.nigil_profile_image.setPixmap(QtGui.QPixmap("nigil_johnson.jpg"))
        self.nigil_profile_image.setScaledContents(True)
        self.nigil_profile_image.setObjectName("nigil_profile_image")
        self.nigil_profile_image_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.nigil_profile_image_label.setGeometry(QtCore.QRect(160, 340, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nigil_profile_image_label.setFont(font)
        self.nigil_profile_image_label.setObjectName("nigil_profile_image_label")
        self.ngil_profile_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.ngil_profile_label.setGeometry(QtCore.QRect(480, 10, 201, 41))
        self.ngil_profile_label.setObjectName("ngil_profile_label")
        self.nigil_profile_label2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.nigil_profile_label2.setGeometry(QtCore.QRect(360, 60, 391, 51))
        self.nigil_profile_label2.setObjectName("nigil_profile_label2")
        self.nigil_profile_label3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.nigil_profile_label3.setGeometry(QtCore.QRect(450, 130, 321, 51))
        self.nigil_profile_label3.setObjectName("nigil_profile_label3")
        self.nigil_profile_label4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.nigil_profile_label4.setGeometry(QtCore.QRect(440, 190, 301, 61))
        self.nigil_profile_label4.setObjectName("nigil_profile_label4")
        self.nigil_profile_label5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.nigil_profile_label5.setGeometry(QtCore.QRect(390, 260, 331, 51))
        self.nigil_profile_label5.setObjectName("nigil_profile_label5")
        self.nigil_profile_label6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.nigil_profile_label6.setGeometry(QtCore.QRect(390, 330, 311, 51))
        self.nigil_profile_label6.setObjectName("nigil_profile_label6")
        self.nigil_profile_home_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.nigil_profile_home_button.setGeometry(QtCore.QRect(660, 510, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.nigil_profile_home_button.setFont(font)
        self.nigil_profile_home_button.setObjectName("nigil_profile_home_button")
        NigilScreen.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=NigilScreen)
        self.statusbar.setObjectName("statusbar")
        NigilScreen.setStatusBar(self.statusbar)

        self.retranslateUi(NigilScreen)
        QtCore.QMetaObject.connectSlotsByName(NigilScreen)

    def retranslateUi(self, NigilScreen):
        _translate = QtCore.QCoreApplication.translate
        NigilScreen.setWindowTitle(_translate("NigilScreen", "MainWindow"))
        self.nigil_profile_image_label.setText(_translate("NigilScreen", "Nigil Johnson"))
        self.ngil_profile_label.setText(_translate("NigilScreen", "Anarchist"))
        self.nigil_profile_label2.setText(_translate("NigilScreen", "Promises To Tear Down The Government \n"
"Won\'t Replace It With Anything"))
        self.nigil_profile_label3.setText(_translate("NigilScreen", "Unlimited Freedom \n"
"Anything Goes"))
        self.nigil_profile_label4.setText(_translate("NigilScreen", "Perpetual Revolution"))
        self.nigil_profile_label5.setText(_translate("NigilScreen", "Refuses To Show His Face \n"
"No one Knows What He Looks Like"))
        self.nigil_profile_label6.setText(_translate("NigilScreen", "Unclear If Nigil Is His Real Name"))
        self.nigil_profile_home_button.setText(_translate("NigilScreen", "Candidates"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NigilScreen = QtWidgets.QMainWindow()
    ui = Ui_NigilScreen()
    ui.setupUi(NigilScreen)
    NigilScreen.show()
    sys.exit(app.exec())
