# Form implementation generated from reading ui file 'VictorScreen.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VictorScreen(object):
    def setupUi(self, VictorScreen):
        VictorScreen.setObjectName("VictorScreen")
        VictorScreen.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=VictorScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.victor_profile_image = QtWidgets.QLabel(parent=self.centralwidget)
        self.victor_profile_image.setGeometry(QtCore.QRect(0, 10, 311, 311))
        self.victor_profile_image.setStyleSheet("image: url(:/newPrefix/victor_emmanuel_2.png);")
        self.victor_profile_image.setText("")
        self.victor_profile_image.setObjectName("victor_profile_image")
        self.victor_profile_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.victor_profile_label.setGeometry(QtCore.QRect(280, 30, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.victor_profile_label.setFont(font)
        self.victor_profile_label.setObjectName("victor_profile_label")
        self.victor_image_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.victor_image_label.setGeometry(QtCore.QRect(90, 320, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.victor_image_label.setFont(font)
        self.victor_image_label.setObjectName("victor_image_label")
        self.victor_profile_label2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.victor_profile_label2.setGeometry(QtCore.QRect(280, 80, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.victor_profile_label2.setFont(font)
        self.victor_profile_label2.setObjectName("victor_profile_label2")
        self.victor_profile_label3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.victor_profile_label3.setGeometry(QtCore.QRect(280, 120, 311, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.victor_profile_label3.setFont(font)
        self.victor_profile_label3.setObjectName("victor_profile_label3")
        self.victor_profile_label4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.victor_profile_label4.setGeometry(QtCore.QRect(280, 210, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.victor_profile_label4.setFont(font)
        self.victor_profile_label4.setObjectName("victor_profile_label4")
        self.victor_profile_label5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.victor_profile_label5.setGeometry(QtCore.QRect(280, 290, 291, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.victor_profile_label5.setFont(font)
        self.victor_profile_label5.setObjectName("victor_profile_label5")
        self.victor_profile_home_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.victor_profile_home_button.setGeometry(QtCore.QRect(480, 500, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.victor_profile_home_button.setFont(font)
        self.victor_profile_home_button.setObjectName("victor_profile_home_button")
        VictorScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=VictorScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        VictorScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=VictorScreen)
        self.statusbar.setObjectName("statusbar")
        VictorScreen.setStatusBar(self.statusbar)

        self.retranslateUi(VictorScreen)
        QtCore.QMetaObject.connectSlotsByName(VictorScreen)

    def retranslateUi(self, VictorScreen):
        _translate = QtCore.QCoreApplication.translate
        VictorScreen.setWindowTitle(_translate("VictorScreen", "MainWindow"))
        self.victor_profile_label.setText(_translate("VictorScreen", "Traditional Monarchist"))
        self.victor_image_label.setText(_translate("VictorScreen", "Victor Emmanuel II"))
        self.victor_profile_label2.setText(_translate("VictorScreen", "Descended From Italian Royalty"))
        self.victor_profile_label3.setText(_translate("VictorScreen", "Intends to reorganize The American Government \n"
"Into A Unified Monarchy"))
        self.victor_profile_label4.setText(_translate("VictorScreen", "Throne will be inherited by his son.\n"
"No more presidents"))
        self.victor_profile_label5.setText(_translate("VictorScreen", "Believes Democracy Has Failed \n"
"His Country and His People "))
        self.victor_profile_home_button.setText(_translate("VictorScreen", "HOME"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VictorScreen = QtWidgets.QMainWindow()
    ui = Ui_VictorScreen()
    ui.setupUi(VictorScreen)
    VictorScreen.show()
    sys.exit(app.exec())
