# Form implementation generated from reading ui file 'VoteScreen.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VoteScreen(object):
    def setupUi(self, VoteScreen):
        VoteScreen.setObjectName("VoteScreen")
        VoteScreen.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(16)
        VoteScreen.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=VoteScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.EmmanuelPicture = QtWidgets.QLabel(parent=self.centralwidget)
        self.EmmanuelPicture.setGeometry(QtCore.QRect(0, 20, 281, 171))
        self.EmmanuelPicture.setStyleSheet("image: url(:/newPrefix/Ritratto_di_S.M._Vittorio_Emanuele_II (2).jpg);")
        self.EmmanuelPicture.setText("")
        self.EmmanuelPicture.setObjectName("EmmanuelPicture")
        self.victor_vote_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.victor_vote_label.setGeometry(QtCore.QRect(220, 20, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.victor_vote_label.setFont(font)
        self.victor_vote_label.setObjectName("victor_vote_label")
        self.victor_vote_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.victor_vote_button.setGeometry(QtCore.QRect(440, 40, 82, 17))
        self.victor_vote_button.setText("")
        self.victor_vote_button.setObjectName("victor_vote_button")
        self.DonPicture = QtWidgets.QLabel(parent=self.centralwidget)
        self.DonPicture.setGeometry(QtCore.QRect(50, 210, 181, 161))
        self.DonPicture.setStyleSheet("image: url(:/newPrefix/DonBeyer2.jpg);")
        self.DonPicture.setText("")
        self.DonPicture.setObjectName("DonPicture")
        self.don_vote_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.don_vote_label.setGeometry(QtCore.QRect(250, 230, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.don_vote_label.setFont(font)
        self.don_vote_label.setObjectName("don_vote_label")
        self.don_vote_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.don_vote_button.setGeometry(QtCore.QRect(390, 260, 82, 17))
        self.don_vote_button.setText("")
        self.don_vote_button.setObjectName("don_vote_button")
        self.NigilPicture = QtWidgets.QLabel(parent=self.centralwidget)
        self.NigilPicture.setGeometry(QtCore.QRect(40, 390, 201, 171))
        self.NigilPicture.setStyleSheet("image: url(:/newPrefix/baltimore-riot.jpg);")
        self.NigilPicture.setText("")
        self.NigilPicture.setObjectName("NigilPicture")
        self.nigil_vote_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.nigil_vote_label.setGeometry(QtCore.QRect(250, 410, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nigil_vote_label.setFont(font)
        self.nigil_vote_label.setObjectName("nigil_vote_label")
        self.nigil_vote_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.nigil_vote_button.setGeometry(QtCore.QRect(430, 430, 82, 17))
        self.nigil_vote_button.setText("")
        self.nigil_vote_button.setObjectName("nigil_vote_button")
        self.vote_home_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.vote_home_button.setGeometry(QtCore.QRect(390, 520, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.vote_home_button.setFont(font)
        self.vote_home_button.setObjectName("vote_home_button")
        self.submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(490, 520, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        VoteScreen.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=VoteScreen)
        self.statusbar.setObjectName("statusbar")
        VoteScreen.setStatusBar(self.statusbar)

        self.retranslateUi(VoteScreen)
        QtCore.QMetaObject.connectSlotsByName(VoteScreen)

    def retranslateUi(self, VoteScreen):
        _translate = QtCore.QCoreApplication.translate
        VoteScreen.setWindowTitle(_translate("VoteScreen", "MainWindow"))
        self.victor_vote_label.setText(_translate("VoteScreen", "Victor Emmanuel II"))
        self.don_vote_label.setText(_translate("VoteScreen", "Don Beyer"))
        self.nigil_vote_label.setText(_translate("VoteScreen", "Nigil Johnson"))
        self.vote_home_button.setText(_translate("VoteScreen", "HOME"))
        self.submit_button.setText(_translate("VoteScreen", "SUBMIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VoteScreen = QtWidgets.QMainWindow()
    ui = Ui_VoteScreen()
    ui.setupUi(VoteScreen)
    VoteScreen.show()
    sys.exit(app.exec())
